version: '3.4'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ddd_demo
    ports:
            - "13306:3306"
