// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: in/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type G2S_UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *G2S_UserInfo) Reset() {
	*x = G2S_UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2S_UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2S_UserInfo) ProtoMessage() {}

func (x *G2S_UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_in_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2S_UserInfo.ProtoReflect.Descriptor instead.
func (*G2S_UserInfo) Descriptor() ([]byte, []int) {
	return file_in_user_proto_rawDescGZIP(), []int{0}
}

func (x *G2S_UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type S2G_UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *UserDTO `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *S2G_UserInfo) Reset() {
	*x = S2G_UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2G_UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2G_UserInfo) ProtoMessage() {}

func (x *S2G_UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_in_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2G_UserInfo.ProtoReflect.Descriptor instead.
func (*S2G_UserInfo) Descriptor() ([]byte, []int) {
	return file_in_user_proto_rawDescGZIP(), []int{1}
}

func (x *S2G_UserInfo) GetUser() *UserDTO {
	if x != nil {
		return x.User
	}
	return nil
}

type UserDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *UserDTO) Reset() {
	*x = UserDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_in_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDTO) ProtoMessage() {}

func (x *UserDTO) ProtoReflect() protoreflect.Message {
	mi := &file_in_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDTO.ProtoReflect.Descriptor instead.
func (*UserDTO) Descriptor() ([]byte, []int) {
	return file_in_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserDTO) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_in_user_proto protoreflect.FileDescriptor

var file_in_user_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x6e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x1e, 0x0a, 0x0c, 0x47, 0x32, 0x53, 0x5f, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x0c, 0x53, 0x32, 0x47, 0x5f, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x54, 0x4f, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x35, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72,
	0x44, 0x54, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x32,
	0x3c, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x32, 0x53, 0x5f, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53,
	0x32, 0x47, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x42, 0x10, 0x5a,
	0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x69, 0x6e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_in_user_proto_rawDescOnce sync.Once
	file_in_user_proto_rawDescData = file_in_user_proto_rawDesc
)

func file_in_user_proto_rawDescGZIP() []byte {
	file_in_user_proto_rawDescOnce.Do(func() {
		file_in_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_in_user_proto_rawDescData)
	})
	return file_in_user_proto_rawDescData
}

var file_in_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_in_user_proto_goTypes = []interface{}{
	(*G2S_UserInfo)(nil), // 0: user.G2S_UserInfo
	(*S2G_UserInfo)(nil), // 1: user.S2G_UserInfo
	(*UserDTO)(nil),      // 2: user.UserDTO
}
var file_in_user_proto_depIdxs = []int32{
	2, // 0: user.S2G_UserInfo.user:type_name -> user.UserDTO
	0, // 1: user.User.UserInfo:input_type -> user.G2S_UserInfo
	1, // 2: user.User.UserInfo:output_type -> user.S2G_UserInfo
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_in_user_proto_init() }
func file_in_user_proto_init() {
	if File_in_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_in_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2S_UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_in_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2G_UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_in_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_in_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_in_user_proto_goTypes,
		DependencyIndexes: file_in_user_proto_depIdxs,
		MessageInfos:      file_in_user_proto_msgTypes,
	}.Build()
	File_in_user_proto = out.File
	file_in_user_proto_rawDesc = nil
	file_in_user_proto_goTypes = nil
	file_in_user_proto_depIdxs = nil
}
